/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.SwingUtilities;

/**
 *
 * @author BRANDON
 */
public class Frm_menu_principal extends javax.swing.JFrame {

    /**
     * Creates new form Frm_menu_principal
     */
    CardLayout vista;
    Pnl_alta_profesor pnl_alta_profesor = new Pnl_alta_profesor();
    Pnl_reporte_profesor pnl_busqueda_profesor = new Pnl_reporte_profesor();
    Pnl_eliminar_profesor pnl_eliminar_profesor = new Pnl_eliminar_profesor();
    Pnl_modificaciones_profesor pnl_modificaciones_profesor = new Pnl_modificaciones_profesor();

    public Frm_menu_principal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        vista = (CardLayout) pnl_vista_principal.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_Baja = new javax.swing.JToggleButton();
        btn_Modificar = new javax.swing.JToggleButton();
        btn_Reporte = new javax.swing.JToggleButton();
        btn_Alta = new javax.swing.JToggleButton();
        btn_Salir = new javax.swing.JToggleButton();
        pnl_vista_principal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Menu del sistema");

        btn_Baja.setBackground(new java.awt.Color(204, 204, 204));
        btn_Baja.setText("Baja");
        btn_Baja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BajaActionPerformed(evt);
            }
        });

        btn_Modificar.setBackground(new java.awt.Color(204, 204, 204));
        btn_Modificar.setText("Modificar");
        btn_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ModificarActionPerformed(evt);
            }
        });

        btn_Reporte.setBackground(new java.awt.Color(204, 204, 204));
        btn_Reporte.setText("Reporte");
        btn_Reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReporteActionPerformed(evt);
            }
        });

        btn_Alta.setBackground(new java.awt.Color(204, 204, 204));
        btn_Alta.setText("Alta");
        btn_Alta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Alta.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_Alta.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn_Alta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AltaActionPerformed(evt);
            }
        });

        btn_Salir.setBackground(new java.awt.Color(204, 204, 204));
        btn_Salir.setText("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Baja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Reporte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Alta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btn_Alta, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Baja, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        pnl_vista_principal.setBackground(new java.awt.Color(204, 255, 255));
        pnl_vista_principal.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl_vista_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_vista_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_SalirActionPerformed

    private void btn_AltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AltaActionPerformed
        // TODO add your handling code here:
        if (btn_Alta.isSelected()) {

            pnl_vista_principal.add(pnl_alta_profesor, "alta");
            vista.show(pnl_vista_principal, "alta");
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            btn_Reporte.setEnabled(false);
            btn_Baja.setEnabled(false);
            btn_Modificar.setEnabled(false);
            btn_Alta.setBackground(Color.WHITE);
            pnl_alta_profesor.limpiar();

        } else {
            pnl_vista_principal.removeAll();
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            btn_Reporte.setEnabled(true);
            btn_Baja.setEnabled(true);
            btn_Modificar.setEnabled(true);
            btn_Alta.setBackground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_btn_AltaActionPerformed

    private void btn_BajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BajaActionPerformed
        // TODO add your handling code here:
        if (btn_Baja.isEnabled()) {

            pnl_vista_principal.add(pnl_eliminar_profesor, "Baja");
            vista.show(pnl_vista_principal, "Baja");
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            btn_Reporte.setEnabled(false);
            btn_Modificar.setEnabled(false);
            btn_Alta.setEnabled(false);
            btn_Baja.setBackground(Color.WHITE);
            pnl_eliminar_profesor.txtCurpBuscarEliminar.setText("");
            pnl_eliminar_profesor.limpiar();
            pnl_eliminar_profesor.limpiarcaja();

        } else {
            pnl_vista_principal.removeAll();
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            btn_Reporte.setEnabled(true);
            btn_Alta.setEnabled(true);
            btn_Modificar.setEnabled(true);
            btn_Baja.setBackground(new Color(204, 204, 204));

        }
    }//GEN-LAST:event_btn_BajaActionPerformed

    private void btn_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ModificarActionPerformed
        // TODO add your handling code here:
        if (btn_Modificar.isEnabled()) {

            pnl_vista_principal.add(pnl_modificaciones_profesor, "Modificacion");
            vista.show(pnl_vista_principal, "Modificacion");
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            btn_Reporte.setEnabled(false);
            btn_Baja.setEnabled(false);
            btn_Alta.setEnabled(false);
            btn_Modificar.setBackground(new Color(204, 204, 204));
            pnl_modificaciones_profesor.borrar();
            pnl_modificaciones_profesor.borrar2();

        } else {
            pnl_vista_principal.removeAll();
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            btn_Reporte.setEnabled(true);
            btn_Alta.setEnabled(true);
            btn_Baja.setEnabled(true);
            btn_Modificar.setBackground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_btn_ModificarActionPerformed

    private void btn_ReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReporteActionPerformed
        // TODO add your handling code here:

        if (btn_Reporte.isEnabled()) {

            pnl_vista_principal.add(pnl_busqueda_profesor, "Buscar");
            vista.show(pnl_vista_principal, "Buscar");
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            btn_Modificar.setEnabled(false);
            btn_Baja.setEnabled(false);
            btn_Alta.setEnabled(false);
            btn_Reporte.setBackground(new Color(204, 204, 204));
        } else {
            pnl_vista_principal.removeAll();
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            btn_Modificar.setEnabled(false);
            btn_Baja.setEnabled(false);
            btn_Alta.setEnabled(false);
            btn_Reporte.setBackground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_btn_ReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_menu_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_Alta;
    private javax.swing.JToggleButton btn_Baja;
    private javax.swing.JToggleButton btn_Modificar;
    private javax.swing.JToggleButton btn_Reporte;
    private javax.swing.JToggleButton btn_Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnl_vista_principal;
    // End of variables declaration//GEN-END:variables
}
