/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.SwingUtilities;

/**
 *
 * @author BRANDON
 */
public class Frm_menu_principal_carrera extends javax.swing.JFrame {

    /**
     * Creates new form Frm_menu_principal_carrera
     */
    CardLayout vista;
    Pnl_alta_profesor pnl_alta_profesor = new Pnl_alta_profesor();
    Pnl_eliminar_carrea pnl_eliminar_carrea = new Pnl_eliminar_carrea();
    
    public Frm_menu_principal_carrera() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        vista = (CardLayout) pnl_vista_principal.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_Altas = new javax.swing.JToggleButton();
        btn_Bajas = new javax.swing.JToggleButton();
        btn_Modificaciones = new javax.swing.JToggleButton();
        btn_Reportes = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        pnl_vista_principal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Menu");

        btn_Altas.setBackground(new java.awt.Color(204, 204, 204));
        btn_Altas.setText("Altas");
        btn_Altas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AltasActionPerformed(evt);
            }
        });

        btn_Bajas.setBackground(new java.awt.Color(204, 204, 204));
        btn_Bajas.setText("Bajas");
        btn_Bajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BajasActionPerformed(evt);
            }
        });

        btn_Modificaciones.setBackground(new java.awt.Color(204, 204, 204));
        btn_Modificaciones.setText("Modificaciones");

        btn_Reportes.setBackground(new java.awt.Color(204, 204, 204));
        btn_Reportes.setText("Reportes");

        jToggleButton5.setText("Salir");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_Bajas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Altas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Modificaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(btn_Reportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jToggleButton5)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Altas)
                .addGap(56, 56, 56)
                .addComponent(btn_Bajas)
                .addGap(55, 55, 55)
                .addComponent(btn_Modificaciones)
                .addGap(58, 58, 58)
                .addComponent(btn_Reportes)
                .addGap(41, 41, 41)
                .addComponent(jToggleButton5)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pnl_vista_principal.setBackground(new java.awt.Color(51, 51, 255));
        pnl_vista_principal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        pnl_vista_principal.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl_vista_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnl_vista_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AltasActionPerformed
        // TODO add your handling code here:
        if (btn_Altas.isSelected()) {

            pnl_vista_principal.add(pnl_alta_profesor, "alta");
            vista.show(pnl_vista_principal, "alta");
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            btn_Reportes.setEnabled(false);
            btn_Bajas.setEnabled(false);
            btn_Modificaciones.setEnabled(false);
            btn_Altas.setBackground(Color.WHITE);
            pnl_alta_profesor.limpiar();

        } else {
            pnl_vista_principal.removeAll();
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            btn_Reportes.setEnabled(true);
            btn_Bajas.setEnabled(true);
            btn_Modificaciones.setEnabled(true);
            btn_Altas.setBackground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_btn_AltasActionPerformed

    private void btn_BajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BajasActionPerformed
        // TODO add your handling code here:
        if (btn_Bajas.isEnabled()) {

            pnl_vista_principal.add(pnl_eliminar_carrea, "Baja");
            vista.show(pnl_vista_principal, "Baja");
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            btn_Reportes.setEnabled(false);
            btn_Modificaciones.setEnabled(false);
            btn_Altas.setEnabled(false);
            btn_Bajas.setBackground(Color.WHITE);
            pnl_eliminar_carrea.txtClaveBuscarEliminar.setText("");
            pnl_eliminar_carrea.limpiar();
            pnl_eliminar_carrea.limpiarcaja();

        } else {
            pnl_vista_principal.removeAll();
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            btn_Reportes.setEnabled(true);
            btn_Altas.setEnabled(true);
            btn_Modificaciones.setEnabled(true);
            btn_Bajas.setBackground(new Color(204, 204, 204));

        }
    }//GEN-LAST:event_btn_BajasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_menu_principal_carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_menu_principal_carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_menu_principal_carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_menu_principal_carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_menu_principal_carrera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_Altas;
    private javax.swing.JToggleButton btn_Bajas;
    private javax.swing.JToggleButton btn_Modificaciones;
    private javax.swing.JToggleButton btn_Reportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JPanel pnl_vista_principal;
    // End of variables declaration//GEN-END:variables
}
