/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Formularios;

import SQL.Conexion_BD;
import SQL.Metodos_SQL;
import java.awt.Component;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author BRANDON
 */
public class Pnl_eliminar_carrea extends javax.swing.JPanel {

    /**
     * Creates new form Pnl_eliminar_carrea
     */
    public Pnl_eliminar_carrea() {
        initComponents();
        bloquear();
    }
    
    private static Connection conexion;
    private static PreparedStatement sentencia_preparada;
    private static ResultSet resultado;
    
    Metodos_SQL metodos_sql = new Metodos_SQL();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void bloquear(){
        for (Component a :pnl_eliminacion_datos.getComponents()) {
            a.setEnabled(false);
            
        }
        for(Component b : pnl_opciones_eliminar.getComponents()){
            b.setEnabled(false);
        }
        
    }
    
    public void desbloquear(){
         for (Component a :pnl_eliminacion_datos.getComponents()) {
            a.setEnabled(true);
            
        }
        for(Component b : pnl_opciones_eliminar.getComponents()){
            b.setEnabled(true);
        }
    }
    public void limpiar(){
        
        lblIdEliminar.setText("---");
        lblNombreEliminar.setText("---");
        
        
        
    }
    
    public void buscarEliminarProfesor(String clave){
        try {
            conexion = Conexion_BD.conectar();
            String sql_busqueda_eliminacion = "SELECT * FROM carrera WHERE clave = ?";
            sentencia_preparada = conexion.prepareStatement(sql_busqueda_eliminacion);
            sentencia_preparada.setString(3, clave);
            resultado = sentencia_preparada.executeQuery();
            if (resultado.next()) {
                lblMensajeEliminar.setText("¡ATENCION: Clave REGISTRADO!");
                lblNombreEliminar.setText(resultado.getString("nombre_carrera"));
                lblIdEliminar.setText(resultado.getString("id"));
                desbloquear();
                
                
            }else{
                lblMensajeEliminar.setText("Sin resultados en la busqueda filtrada");
                bloquear();
                limpiar();
            }
            conexion.close();
        } catch (SQLException e) {
            System.out.println("Erro: "  + e);
        }finally{
            try {
                conexion.close();
            } catch (SQLException ex) {
                Logger.getLogger(Pnl_eliminar_profesor.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Error: " + ex);
            }
        }
        limpiarcaja();
    }
    
    public void limpiarcaja(){
        if (txtClaveBuscarEliminar.getText().isEmpty()) {
            lblMensajeEliminar.setText("");
            limpiar();
        }
    }
    
     public void eliminarCarreraPregunta(){
        int pregunta;
        pregunta = JOptionPane.showConfirmDialog(null, "¿Realmente desea eliminar la carrera de la Base De Datos?","Confirmar Borrado",JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        
        if (pregunta == 0) {
            metodos_sql.eliminarProfesor(txtClaveBuscarEliminar.getText());
            txtClaveBuscarEliminar.setText("");
            limpiar();
            limpiarcaja();
            bloquear();
        }   
    }
     
     public void clausula_caja_texto(java.awt.event.KeyEvent evt){
        Character  a = evt.getKeyChar();
        if (Character.isLetter(a)) {
            evt.setKeyChar(Character.toUpperCase(a));
        }
        if (txtClaveBuscarEliminar.getText().length()>= 18 ) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }
    
     
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnl_eliminacion_datos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblIdEliminar = new javax.swing.JTextField();
        lblNombreEliminar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtClaveBuscarEliminar = new javax.swing.JTextField();
        pnl_opciones_eliminar = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblMensajeEliminar = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Baja de carrera");

        pnl_eliminacion_datos.setBackground(new java.awt.Color(255, 255, 255));
        pnl_eliminacion_datos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inserte los datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jLabel3.setText("ID:");

        jLabel4.setText("Nombre de la carrera:");

        lblIdEliminar.setText("---");

        lblNombreEliminar.setText("---");

        javax.swing.GroupLayout pnl_eliminacion_datosLayout = new javax.swing.GroupLayout(pnl_eliminacion_datos);
        pnl_eliminacion_datos.setLayout(pnl_eliminacion_datosLayout);
        pnl_eliminacion_datosLayout.setHorizontalGroup(
            pnl_eliminacion_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_eliminacion_datosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_eliminacion_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_eliminacion_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        pnl_eliminacion_datosLayout.setVerticalGroup(
            pnl_eliminacion_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_eliminacion_datosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnl_eliminacion_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblIdEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(pnl_eliminacion_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblNombreEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Inserte la Clave para eliminar datos");

        txtClaveBuscarEliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClaveBuscarEliminarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClaveBuscarEliminarKeyTyped(evt);
            }
        });

        pnl_opciones_eliminar.setBackground(new java.awt.Color(255, 255, 255));
        pnl_opciones_eliminar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        btnEliminar.setText("Eliminar Carrera");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jButton2.setText("Reiniciar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_opciones_eliminarLayout = new javax.swing.GroupLayout(pnl_opciones_eliminar);
        pnl_opciones_eliminar.setLayout(pnl_opciones_eliminarLayout);
        pnl_opciones_eliminarLayout.setHorizontalGroup(
            pnl_opciones_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_opciones_eliminarLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(pnl_opciones_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar))
                .addGap(37, 37, 37))
        );
        pnl_opciones_eliminarLayout.setVerticalGroup(
            pnl_opciones_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_opciones_eliminarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnEliminar)
                .addGap(35, 35, 35)
                .addComponent(jButton2)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        lblMensajeEliminar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMensajeEliminar.setText("---");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnl_eliminacion_datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnl_opciones_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtClaveBuscarEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblMensajeEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtClaveBuscarEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMensajeEliminar))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_opciones_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_eliminacion_datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        eliminarCarreraPregunta();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtClaveBuscarEliminarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveBuscarEliminarKeyReleased
        // TODO add your handling code here:
        buscarEliminarProfesor(txtClaveBuscarEliminar.getText());
    }//GEN-LAST:event_txtClaveBuscarEliminarKeyReleased

    private void txtClaveBuscarEliminarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveBuscarEliminarKeyTyped
        // TODO add your handling code here:
         clausula_caja_texto(evt);
    }//GEN-LAST:event_txtClaveBuscarEliminarKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtClaveBuscarEliminar.setText("");
        limpiarcaja();
        limpiar();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lblIdEliminar;
    private javax.swing.JLabel lblMensajeEliminar;
    private javax.swing.JTextField lblNombreEliminar;
    private javax.swing.JPanel pnl_eliminacion_datos;
    private javax.swing.JPanel pnl_opciones_eliminar;
    public javax.swing.JTextField txtClaveBuscarEliminar;
    // End of variables declaration//GEN-END:variables
}
