/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Formularios;

import SQL.Metodos_SQL;
import java.awt.Toolkit;

/**
 *
 * @author BRANDON
 */
public class Pnl_alta_profesor extends javax.swing.JPanel {

    /**
     * Creates new form Pnl_alta_profesor
     */
    Metodos_SQL metodos_SQL = new Metodos_SQL();
    
    int  id;
    int numeroEmpleado;
    String curp;
    String nombre;
    String apellidoP;
    String apellidoM;
    String email;
    String gradoEstudio;
    String rfc;
    String materias;
    String carrera;
    
    
    public Pnl_alta_profesor() {
        initComponents();
        btnGuardar.setEnabled(false);
        
    }
    
    public void limpiar(){
        txtIdAlta.setText("");
        txtNumeroEmpleadoAlta.setText("");
        txtNombreAlta.setText("");
        txtApellidoPAlta.setText("");
        txtApellidoMAlta.setText("");
        txtCurpAlta.setText("");
        txtEmailAlta.setText("");
        txtGradoEstudioAlta.setText("");
        txtRfcAlta.setText("");
        txtMateriasAlta.setText("");
        txtCarreraAlta.setText("");
        lblCurpInformacionCaracteres.setText("");
        lblInformacionCurpBusqueda.setText("");
    }
    
    public void validacion(){
        String mensaje = metodos_SQL.buscarCurp(txtCurpAlta.getText());
        
        if (mensaje.equals("Existe Curp")) {
            lblInformacionCurpBusqueda.setText("<html><center>EL CURP ya se encuentra registrado");
        }else{
          lblInformacionCurpBusqueda.setText("CURP No registrado");  
        }
        
        if (txtCurpAlta.getText().length()< 18) {
            lblCurpInformacionCaracteres.setText("<html><center> El CURP debe cumplir con un minimo de 18 caracteres");
        }else{
            lblCurpInformacionCaracteres.setText("CURP valido");
        }
        
        
        if (txtApellidoPAlta.getText().isEmpty() || txtNombreAlta.getText().isEmpty() || txtApellidoMAlta.getText().isEmpty() || txtCurpAlta.getText().isEmpty() || txtIdAlta.getText().isEmpty() || txtMateriasAlta.getText().isEmpty() || txtCarreraAlta.getText().isEmpty() || txtRfcAlta.getText().isEmpty() || txtEmailAlta.getText().isEmpty() || txtNumeroEmpleadoAlta.getText().isEmpty() || txtGradoEstudioAlta.getText().isEmpty() || txtCurpAlta.getText().isEmpty()) {
            btnGuardar.setEnabled(false);
        }else{
            btnGuardar.setEnabled(true);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtIdAlta = new javax.swing.JTextField();
        txtNombreAlta = new javax.swing.JTextField();
        txtNumeroEmpleadoAlta = new javax.swing.JTextField();
        txtApellidoPAlta = new javax.swing.JTextField();
        txtCurpAlta = new javax.swing.JTextField();
        txtApellidoMAlta = new javax.swing.JTextField();
        txtEmailAlta = new javax.swing.JTextField();
        txtRfcAlta = new javax.swing.JTextField();
        txtGradoEstudioAlta = new javax.swing.JTextField();
        txtMateriasAlta = new javax.swing.JTextField();
        txtCarreraAlta = new javax.swing.JTextField();
        lblInformacionCurpBusqueda = new javax.swing.JLabel();
        lblCurpInformacionCaracteres = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Alta de nuevo profesor");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inserte datos del profesor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Numero de empleado:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Apellido Paterno:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Nombre:");

        jLabel6.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel6.setText("Apellido Materno:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("CURP:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Email:");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Grado de estudios:");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("RFC:");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Materias:");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Carrera:");

        txtIdAlta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtIdAlta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdAltaKeyReleased(evt);
            }
        });

        txtNombreAlta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtNombreAlta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreAltaKeyReleased(evt);
            }
        });

        txtNumeroEmpleadoAlta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtNumeroEmpleadoAlta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumeroEmpleadoAltaKeyReleased(evt);
            }
        });

        txtApellidoPAlta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtApellidoPAlta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoPAltaKeyReleased(evt);
            }
        });

        txtCurpAlta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCurpAlta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCurpAltaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCurpAltaKeyTyped(evt);
            }
        });

        txtApellidoMAlta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtApellidoMAlta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoMAltaKeyReleased(evt);
            }
        });

        txtEmailAlta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtEmailAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailAltaActionPerformed(evt);
            }
        });
        txtEmailAlta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailAltaKeyReleased(evt);
            }
        });

        txtRfcAlta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtRfcAlta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRfcAltaKeyReleased(evt);
            }
        });

        txtGradoEstudioAlta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtGradoEstudioAlta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGradoEstudioAltaKeyReleased(evt);
            }
        });

        txtMateriasAlta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtMateriasAlta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMateriasAltaKeyReleased(evt);
            }
        });

        txtCarreraAlta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCarreraAlta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCarreraAltaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumeroEmpleadoAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCarreraAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMateriasAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRfcAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCurpAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoPAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoMAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGradoEstudioAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtIdAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCurpInformacionCaracteres, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(lblInformacionCurpBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInformacionCurpBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCurpInformacionCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNumeroEmpleadoAlta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtNombreAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addComponent(txtApellidoPAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtApellidoMAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCurpAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addComponent(txtEmailAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtGradoEstudioAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(txtRfcAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtMateriasAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtCarreraAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        btnGuardar.setBackground(new java.awt.Color(204, 204, 204));
        btnGuardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBorrar.setBackground(new java.awt.Color(204, 204, 204));
        btnBorrar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        id = Integer.parseInt(txtIdAlta.getText());
        numeroEmpleado = Integer.parseInt(txtNumeroEmpleadoAlta.getText());
        nombre = txtNombreAlta.getText();
        apellidoP = txtApellidoPAlta.getText();
        apellidoM = txtApellidoMAlta.getText();
        curp = txtCurpAlta.getText();
        email = txtEmailAlta.getText();
        gradoEstudio = txtGradoEstudioAlta.getText();
        rfc = txtRfcAlta.getText();
        materias = txtMateriasAlta.getText();
        carrera = txtCarreraAlta.getText();
        
        
        
        
        
        metodos_SQL.guardar_datos_profesor(id, numeroEmpleado, nombre, apellidoP, apellidoM, curp, email, gradoEstudio, rfc, materias, carrera);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtEmailAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailAltaActionPerformed

    private void txtCurpAltaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCurpAltaKeyReleased
        // TODO add your handling code here:
        validacion();
    }//GEN-LAST:event_txtCurpAltaKeyReleased

    private void txtCurpAltaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCurpAltaKeyTyped
        // TODO add your handling code here:
        Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
        if (txtCurpAlta.getText().length() >= 18) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        
    }//GEN-LAST:event_txtCurpAltaKeyTyped

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void txtIdAltaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdAltaKeyReleased
        // TODO add your handling code here
        validacion();
    }//GEN-LAST:event_txtIdAltaKeyReleased

    private void txtNumeroEmpleadoAltaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroEmpleadoAltaKeyReleased
        // TODO add your handling code here
         validacion();
    }//GEN-LAST:event_txtNumeroEmpleadoAltaKeyReleased

    private void txtNombreAltaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreAltaKeyReleased
        // TODO add your handling code here:
         validacion();
    }//GEN-LAST:event_txtNombreAltaKeyReleased

    private void txtApellidoPAltaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoPAltaKeyReleased
        // TODO add your handling code here:
         validacion();
    }//GEN-LAST:event_txtApellidoPAltaKeyReleased

    private void txtApellidoMAltaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoMAltaKeyReleased
        // TODO add your handling code here:
         validacion();
    }//GEN-LAST:event_txtApellidoMAltaKeyReleased

    private void txtEmailAltaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailAltaKeyReleased
        // TODO add your handling code here:
         validacion();
    }//GEN-LAST:event_txtEmailAltaKeyReleased

    private void txtGradoEstudioAltaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGradoEstudioAltaKeyReleased
        // TODO add your handling code here:
         validacion();
    }//GEN-LAST:event_txtGradoEstudioAltaKeyReleased

    private void txtRfcAltaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRfcAltaKeyReleased
        // TODO add your handling code here:
         validacion();
    }//GEN-LAST:event_txtRfcAltaKeyReleased

    private void txtMateriasAltaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMateriasAltaKeyReleased
        // TODO add your handling code here:
         validacion();
    }//GEN-LAST:event_txtMateriasAltaKeyReleased

    private void txtCarreraAltaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCarreraAltaKeyReleased
        // TODO add your handling code here:
         validacion();
    }//GEN-LAST:event_txtCarreraAltaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCurpInformacionCaracteres;
    private javax.swing.JLabel lblInformacionCurpBusqueda;
    private javax.swing.JTextField txtApellidoMAlta;
    private javax.swing.JTextField txtApellidoPAlta;
    private javax.swing.JTextField txtCarreraAlta;
    private javax.swing.JTextField txtCurpAlta;
    private javax.swing.JTextField txtEmailAlta;
    private javax.swing.JTextField txtGradoEstudioAlta;
    private javax.swing.JTextField txtIdAlta;
    private javax.swing.JTextField txtMateriasAlta;
    private javax.swing.JTextField txtNombreAlta;
    private javax.swing.JTextField txtNumeroEmpleadoAlta;
    private javax.swing.JTextField txtRfcAlta;
    // End of variables declaration//GEN-END:variables
}

