/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Formularios;

import SQL.Metodos_SQL;
import java.awt.Component;
import java.awt.Toolkit;

/**
 *
 * @author BRANDON
 */
public class Pnl_modificaciones_profesor extends javax.swing.JPanel {

    /**
     * Creates new form Pnl_modificaciones_profesor
     */
    public Pnl_modificaciones_profesor() {
        initComponents();
        bloquear();
    }

    Metodos_SQL metodos_sql = new Metodos_SQL();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void borrar() {
        txtApellidoMActualizar.setText("");
        txtApellidoPActualizar.setText("");
        txtCarreraActualizar.setText("");
        //txtCurpBuscarDatosActualizar.setText("");
        txtEmailActualizar.setText("");
        txtGradoEstudiosActualizar.setText("");
        txtIdActualizar.setText("");
        txtMateriasActualizar.setText("");
        txtNombreActualizar.setText("");
        txtRfcActualizar.setText("");
        txtGradoEstudiosActualizar.setText("");
        bloquear();
    }

    public void busqueda_usuario() {
        String curp = txtCurpBuscarDatosActualizar.getText();
        metodos_sql.buscarCurp(curp);
        String mensaje = metodos_sql.buscarCurp(curp);
        if (mensaje.equals("Existe Curp")) {
            lblInformacionAcualizar.setText("Curp Encontrado, Se pude actualizar el dato");
            desbloquear();
        } else {
            lblInformacionAcualizar.setText("Sin resultados en la busqueda");
            bloquear();
            borrar();
        }
        if(txtCurpBuscarDatosActualizar.getText().isEmpty()){
           lblInformacionAcualizar.setText("");  
        }
    }

    public void modificar_datos() {
        String curp = txtCurpBuscarDatosActualizar.getText();
        String nombre = txtNombreActualizar.getText();
        String apellidoP = txtApellidoPActualizar.getText();
        String apellidoM = txtApellidoMActualizar.getText();
        String carrera = txtCarreraActualizar.getText();
        String materias = txtMateriasActualizar.getText();
        String rfc = txtRfcActualizar.getText();
        String email = txtEmailActualizar.getText();
        String gradoEstudio = txtGradoEstudiosActualizar.getText();
        int id = Integer.parseInt(txtIdActualizar.getText());
        int numeroEmpleado = Integer.parseInt(txtNumeroEmpleadoActualizar.getText());

        metodos_sql.modificar_datos_profesor(id, numeroEmpleado, nombre, apellidoP, apellidoM, curp, email, gradoEstudio, rfc, materias, carrera);
        borrar();
        txtCurpBuscarDatosActualizar.setText("");
        lblInformacionAcualizar.setText("");
    }

    public void validacion_busqueda_actualizar(java.awt.event.KeyEvent evt) {
        Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
        if (txtCurpBuscarDatosActualizar.getText().length() >= 18) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }

    public void bloquear() {
        for (Component a : Pnl_Actualizacion_Datos.getComponents()) {
            a.setEnabled(false);
        }
        for (Component b : Pnl_Opciones_Actualizar.getComponents()) {
            b.setEnabled(false);

        }
    }
    
    public void desbloquear() {
        for (Component a : Pnl_Actualizacion_Datos.getComponents()) {
            a.setEnabled(true);
        }
        for (Component b : Pnl_Opciones_Actualizar.getComponents()) {
            b.setEnabled(true);

        }
        validacion_datos();
    }
    
    public void borrar2(){
        lblInformacionAcualizar.setText("");
        txtCurpBuscarDatosActualizar.setText("");
    }
    
    public void validacion_datos(){
        if (txtApellidoMActualizar.getText().isEmpty() || txtApellidoPActualizar.getText().isEmpty() || txtCarreraActualizar.getText().isEmpty() || txtEmailActualizar.getText().isEmpty() || txtGradoEstudiosActualizar.getText().isEmpty() || txtIdActualizar.getText().isEmpty() || txtMateriasActualizar.getText().isEmpty() || txtNombreActualizar.getText().isEmpty() || txtNumeroEmpleadoActualizar.getText().isEmpty() || txtRfcActualizar.getText().isEmpty()) {
            btnActualizar.setEnabled(false);
        }else{
            btnActualizar.setEnabled(true);
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Pnl_Actualizacion_Datos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNombreActualizar = new javax.swing.JTextField();
        txtNumeroEmpleadoActualizar = new javax.swing.JTextField();
        txtApellidoPActualizar = new javax.swing.JTextField();
        txtIdActualizar = new javax.swing.JTextField();
        txtApellidoMActualizar = new javax.swing.JTextField();
        txtEmailActualizar = new javax.swing.JTextField();
        txtRfcActualizar = new javax.swing.JTextField();
        txtGradoEstudiosActualizar = new javax.swing.JTextField();
        txtMateriasActualizar = new javax.swing.JTextField();
        txtCarreraActualizar = new javax.swing.JTextField();
        Pnl_Opciones_Actualizar = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        btnBorrarActualizar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtCurpBuscarDatosActualizar = new javax.swing.JTextField();
        lblInformacionAcualizar = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Actualizacion del profesor");

        Pnl_Actualizacion_Datos.setBackground(new java.awt.Color(255, 255, 255));
        Pnl_Actualizacion_Datos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del profesor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Numero de empleado:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Apellido Paterno:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Nombre:");

        jLabel6.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel6.setText("Apellido Materno:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("ID");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Email:");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Grado de estudios:");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("RFC:");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Materias:");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Carrera:");

        txtNombreActualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtNombreActualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreActualizarKeyReleased(evt);
            }
        });

        txtNumeroEmpleadoActualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtNumeroEmpleadoActualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumeroEmpleadoActualizarKeyReleased(evt);
            }
        });

        txtApellidoPActualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtApellidoPActualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoPActualizarKeyReleased(evt);
            }
        });

        txtIdActualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtIdActualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdActualizarKeyReleased(evt);
            }
        });

        txtApellidoMActualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtApellidoMActualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoMActualizarKeyReleased(evt);
            }
        });

        txtEmailActualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtEmailActualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailActualizarKeyReleased(evt);
            }
        });

        txtRfcActualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtRfcActualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRfcActualizarKeyReleased(evt);
            }
        });

        txtGradoEstudiosActualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtGradoEstudiosActualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGradoEstudiosActualizarKeyReleased(evt);
            }
        });

        txtMateriasActualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtMateriasActualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMateriasActualizarKeyReleased(evt);
            }
        });

        txtCarreraActualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCarreraActualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCarreraActualizarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout Pnl_Actualizacion_DatosLayout = new javax.swing.GroupLayout(Pnl_Actualizacion_Datos);
        Pnl_Actualizacion_Datos.setLayout(Pnl_Actualizacion_DatosLayout);
        Pnl_Actualizacion_DatosLayout.setHorizontalGroup(
            Pnl_Actualizacion_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_Actualizacion_DatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_Actualizacion_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addGroup(Pnl_Actualizacion_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumeroEmpleadoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCarreraActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMateriasActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRfcActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoPActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoMActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGradoEstudiosActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        Pnl_Actualizacion_DatosLayout.setVerticalGroup(
            Pnl_Actualizacion_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_Actualizacion_DatosLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(Pnl_Actualizacion_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNumeroEmpleadoActualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Pnl_Actualizacion_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Pnl_Actualizacion_DatosLayout.createSequentialGroup()
                        .addGroup(Pnl_Actualizacion_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Pnl_Actualizacion_DatosLayout.createSequentialGroup()
                                .addGroup(Pnl_Actualizacion_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtNombreActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addComponent(txtApellidoPActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Pnl_Actualizacion_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtApellidoMActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Pnl_Actualizacion_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtIdActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addComponent(txtEmailActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Pnl_Actualizacion_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtGradoEstudiosActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Pnl_Actualizacion_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(txtRfcActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Pnl_Actualizacion_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtMateriasActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Pnl_Actualizacion_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtCarreraActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        Pnl_Opciones_Actualizar.setBackground(new java.awt.Color(255, 255, 255));
        Pnl_Opciones_Actualizar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        btnActualizar.setBackground(new java.awt.Color(204, 204, 204));
        btnActualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnBorrarActualizar.setBackground(new java.awt.Color(204, 204, 204));
        btnBorrarActualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnBorrarActualizar.setText("Borrar");
        btnBorrarActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pnl_Opciones_ActualizarLayout = new javax.swing.GroupLayout(Pnl_Opciones_Actualizar);
        Pnl_Opciones_Actualizar.setLayout(Pnl_Opciones_ActualizarLayout);
        Pnl_Opciones_ActualizarLayout.setHorizontalGroup(
            Pnl_Opciones_ActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_Opciones_ActualizarLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(Pnl_Opciones_ActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(btnBorrarActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        Pnl_Opciones_ActualizarLayout.setVerticalGroup(
            Pnl_Opciones_ActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_Opciones_ActualizarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnBorrarActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("Inserte el CURP para actualizar datos:");

        txtCurpBuscarDatosActualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCurpBuscarDatosActualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCurpBuscarDatosActualizarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCurpBuscarDatosActualizarKeyTyped(evt);
            }
        });

        lblInformacionAcualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Pnl_Actualizacion_Datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Pnl_Opciones_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txtCurpBuscarDatosActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblInformacionAcualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtCurpBuscarDatosActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInformacionAcualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Pnl_Opciones_Actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pnl_Actualizacion_Datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActualizarActionPerformed
        // TODO add your handling code here:
        borrar();
        borrar2();
    }//GEN-LAST:event_btnBorrarActualizarActionPerformed

    private void txtCurpBuscarDatosActualizarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCurpBuscarDatosActualizarKeyReleased
        // TODO add your handling code here:
        busqueda_usuario();
    }//GEN-LAST:event_txtCurpBuscarDatosActualizarKeyReleased

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        modificar_datos();

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtCurpBuscarDatosActualizarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCurpBuscarDatosActualizarKeyTyped
        // TODO add your handling code here:
        validacion_busqueda_actualizar(evt);
    }//GEN-LAST:event_txtCurpBuscarDatosActualizarKeyTyped

    private void txtNumeroEmpleadoActualizarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroEmpleadoActualizarKeyReleased
        // TODO add your handling code here:
        validacion_datos();
    }//GEN-LAST:event_txtNumeroEmpleadoActualizarKeyReleased

    private void txtNombreActualizarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreActualizarKeyReleased
        // TODO add your handling code here:
        validacion_datos();
    }//GEN-LAST:event_txtNombreActualizarKeyReleased

    private void txtApellidoPActualizarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoPActualizarKeyReleased
        // TODO add your handling code here:
        validacion_datos();
    }//GEN-LAST:event_txtApellidoPActualizarKeyReleased

    private void txtApellidoMActualizarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoMActualizarKeyReleased
        // TODO add your handling code here:
        validacion_datos();
    }//GEN-LAST:event_txtApellidoMActualizarKeyReleased

    private void txtIdActualizarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdActualizarKeyReleased
        // TODO add your handling code here:
        validacion_datos();
    }//GEN-LAST:event_txtIdActualizarKeyReleased

    private void txtEmailActualizarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailActualizarKeyReleased
        // TODO add your handling code here:
        validacion_datos();
    }//GEN-LAST:event_txtEmailActualizarKeyReleased

    private void txtGradoEstudiosActualizarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGradoEstudiosActualizarKeyReleased
        // TODO add your handling code here:
        validacion_datos();
    }//GEN-LAST:event_txtGradoEstudiosActualizarKeyReleased

    private void txtRfcActualizarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRfcActualizarKeyReleased
        // TODO add your handling code here:
        validacion_datos();
    }//GEN-LAST:event_txtRfcActualizarKeyReleased

    private void txtMateriasActualizarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMateriasActualizarKeyReleased
        // TODO add your handling code here:
        validacion_datos();
    }//GEN-LAST:event_txtMateriasActualizarKeyReleased

    private void txtCarreraActualizarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCarreraActualizarKeyReleased
        // TODO add your handling code here:
        validacion_datos();
    }//GEN-LAST:event_txtCarreraActualizarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pnl_Actualizacion_Datos;
    private javax.swing.JPanel Pnl_Opciones_Actualizar;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrarActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lblInformacionAcualizar;
    private javax.swing.JTextField txtApellidoMActualizar;
    private javax.swing.JTextField txtApellidoPActualizar;
    private javax.swing.JTextField txtCarreraActualizar;
    private javax.swing.JTextField txtCurpBuscarDatosActualizar;
    private javax.swing.JTextField txtEmailActualizar;
    private javax.swing.JTextField txtGradoEstudiosActualizar;
    private javax.swing.JTextField txtIdActualizar;
    private javax.swing.JTextField txtMateriasActualizar;
    private javax.swing.JTextField txtNombreActualizar;
    private javax.swing.JTextField txtNumeroEmpleadoActualizar;
    private javax.swing.JTextField txtRfcActualizar;
    // End of variables declaration//GEN-END:variables
}
