/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Formularios;

import SQL.Metodos_SQL;
import java.awt.Component;
import java.awt.Toolkit;

/**
 *
 * @author BRANDON
 */
public class Pnl_modificaciones_carrera extends javax.swing.JPanel {

    /**
     * Creates new form Pnl_modificaciones_carrera
     */
    public Pnl_modificaciones_carrera() {
        initComponents();
        bloquear();
    }
    Metodos_SQL metodos_sql = new Metodos_SQL();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void borrar() {
        
        txtIdActualizar.setText("");
        txtNombreActualizar.setText("");
     
        bloquear();
    }
     public void busqueda_usuario() {
        String clave = txtClaveBuscarDatosActualizar.getText();
        metodos_sql.buscarClave(clave);
        String mensaje = metodos_sql.buscarClave(clave);
        if (mensaje.equals("Existe Curp")) {
            lblInformacionAcualizar.setText("Curp Encontrado, Se pude actualizar el dato");
            desbloquear();
        } else {
            lblInformacionAcualizar.setText("Sin resultados en la busqueda");
            bloquear();
            borrar();
        }
        if(txtClaveBuscarDatosActualizar.getText().isEmpty()){
           lblInformacionAcualizar.setText("");  
        }
    }
     
      public void modificar_datos() {
        String clave = txtClaveBuscarDatosActualizar.getText();
        String nombre = txtNombreActualizar.getText();
        int id = Integer.parseInt(txtIdActualizar.getText());

        metodos_sql.modificar_datos_carrera(id, nombre,clave);
        borrar();
        txtClaveBuscarDatosActualizar.setText("");
        lblInformacionAcualizar.setText("");
    }
      
    public void validacion_busqueda_actualizar(java.awt.event.KeyEvent evt) {
        Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
        if (txtClaveBuscarDatosActualizar.getText().length() >= 5) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }
      
    public void bloquear() {
        for (Component a : Pnl_Actualizacion_Datos.getComponents()) {
            a.setEnabled(false);
        }
        for (Component b : Pnl_Opciones_Actualizar.getComponents()) {
            b.setEnabled(false);

        }
    }
    
    public void desbloquear() {
        for (Component a : Pnl_Actualizacion_Datos.getComponents()) {
            a.setEnabled(true);
        }
        for (Component b : Pnl_Opciones_Actualizar.getComponents()) {
            b.setEnabled(true);

        }
        validacion_datos();
    }
    public void borrar2(){
        lblInformacionAcualizar.setText("");
        txtClaveBuscarDatosActualizar.setText("");
    }
    
    public void validacion_datos(){
        if (txtIdActualizar.getText().isEmpty() || txtNombreActualizar.getText().isEmpty()) {
            btnActualizar.setEnabled(false);
        }else{
            btnActualizar.setEnabled(true);
        }
    }
      
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Pnl_Actualizacion_Datos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdActualizar = new javax.swing.JTextField();
        txtNombreActualizar = new javax.swing.JTextField();
        Pnl_Opciones_Actualizar = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        btnBorrarActualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtClaveBuscarDatosActualizar = new javax.swing.JTextField();
        lblInformacionAcualizar = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Pnl_Actualizacion_Datos.setBackground(new java.awt.Color(255, 255, 255));
        Pnl_Actualizacion_Datos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la carrera"));

        jLabel3.setText("ID:");

        jLabel4.setText("Nombre de la carrera:");

        txtIdActualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdActualizarKeyReleased(evt);
            }
        });

        txtNombreActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pnl_Actualizacion_DatosLayout = new javax.swing.GroupLayout(Pnl_Actualizacion_Datos);
        Pnl_Actualizacion_Datos.setLayout(Pnl_Actualizacion_DatosLayout);
        Pnl_Actualizacion_DatosLayout.setHorizontalGroup(
            Pnl_Actualizacion_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_Actualizacion_DatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_Actualizacion_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGroup(Pnl_Actualizacion_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_Actualizacion_DatosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(txtIdActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(Pnl_Actualizacion_DatosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        Pnl_Actualizacion_DatosLayout.setVerticalGroup(
            Pnl_Actualizacion_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_Actualizacion_DatosLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(Pnl_Actualizacion_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIdActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(Pnl_Actualizacion_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombreActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        Pnl_Opciones_Actualizar.setBackground(new java.awt.Color(255, 255, 255));
        Pnl_Opciones_Actualizar.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnBorrarActualizar.setText("Borrar");
        btnBorrarActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pnl_Opciones_ActualizarLayout = new javax.swing.GroupLayout(Pnl_Opciones_Actualizar);
        Pnl_Opciones_Actualizar.setLayout(Pnl_Opciones_ActualizarLayout);
        Pnl_Opciones_ActualizarLayout.setHorizontalGroup(
            Pnl_Opciones_ActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_Opciones_ActualizarLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(Pnl_Opciones_ActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBorrarActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(97, 97, 97))
        );
        Pnl_Opciones_ActualizarLayout.setVerticalGroup(
            Pnl_Opciones_ActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_Opciones_ActualizarLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnActualizar)
                .addGap(42, 42, 42)
                .addComponent(btnBorrarActualizar)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Actualizacion de la carrera");

        jLabel2.setText("Inserte la Clave para actualizar datos:");

        txtClaveBuscarDatosActualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClaveBuscarDatosActualizarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClaveBuscarDatosActualizarKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtClaveBuscarDatosActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Pnl_Actualizacion_Datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pnl_Opciones_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInformacionAcualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtClaveBuscarDatosActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInformacionAcualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pnl_Opciones_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pnl_Actualizacion_Datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(514, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActualizarActionPerformed
        // TODO add your handling code here:
        borrar();
        borrar2();
    }//GEN-LAST:event_btnBorrarActualizarActionPerformed

    private void txtClaveBuscarDatosActualizarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveBuscarDatosActualizarKeyReleased
        // TODO add your handling code here:
        busqueda_usuario();
    }//GEN-LAST:event_txtClaveBuscarDatosActualizarKeyReleased

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        modificar_datos();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtClaveBuscarDatosActualizarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveBuscarDatosActualizarKeyTyped
        // TODO add your handling code here:
        validacion_busqueda_actualizar(evt);
    }//GEN-LAST:event_txtClaveBuscarDatosActualizarKeyTyped

    private void txtIdActualizarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdActualizarKeyReleased
        // TODO add your handling code here:
        validacion_datos();
    }//GEN-LAST:event_txtIdActualizarKeyReleased

    private void txtNombreActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActualizarActionPerformed
        // TODO add your handling code here:
        validacion_datos();
    }//GEN-LAST:event_txtNombreActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pnl_Actualizacion_Datos;
    private javax.swing.JPanel Pnl_Opciones_Actualizar;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrarActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField lblInformacionAcualizar;
    private javax.swing.JTextField txtClaveBuscarDatosActualizar;
    private javax.swing.JTextField txtIdActualizar;
    private javax.swing.JTextField txtNombreActualizar;
    // End of variables declaration//GEN-END:variables
}
